// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject1
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIXProject1PackageString = "55fe82ca-eefb-4776-9442-049251623a2a";
        public static Guid guidVSIXProject1Package = new Guid(guidVSIXProject1PackageString);

        public const string guidCmdSetString = "53062773-3043-44a9-ba60-f646f408df31";
        public static Guid guidCmdSet = new Guid(guidCmdSetString);

        public const string guidVSIXProject1PackageCmdSetString = "1d48d59a-b75b-4d3e-a9e6-d64cd76391c4";
        public static Guid guidVSIXProject1PackageCmdSet = new Guid(guidVSIXProject1PackageCmdSetString);

        public const string guidVSIXProject1PackageCmdSet1String = "966034e1-2b7b-4876-b0ae-b7ded2abed89";
        public static Guid guidVSIXProject1PackageCmdSet1 = new Guid(guidVSIXProject1PackageCmdSet1String);

        public const string guidImagesString = "fdaa6037-b528-4ec4-9fbe-a23a8d394e9d";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cdrAddonMenu = 0x1030;
        public const int MyMenuGroup = 0x1020;
        public const int CreateTargetsCommandId = 0x0100;
        public const int cmdidOpenAddonFolder = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}